// <auto-generated />
namespace WorkWarriors.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class d7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(d7));
        
        string IMigrationMetadata.Id
        {
            get { return "201609192302559_d7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
